import Head from 'next/head';

const Home = ({data}: {data: IFakeJSON}) => {  
  
  return (
    <div className='root'>
      <Head>
        <title>{data?.title}</title>
      </Head>
      <main>
        {JSON.stringify(data)}
      </main>
      
    </div>
  )
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://jsonplaceholder.typicode.com/todos/1`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}

// Generated by https://quicktype.io

export interface IFakeJSON {
  userId:    number;
  id:        number;
  title:     string;
  completed: boolean;
}


export default Home
